import { ProductAttribute } from '@shared/types/product';

export const mockProductSeed: (response: { id: string }[]) => Promise<ProductAttribute[]> = async (response) => {
  const vendorsId = response.map((u) => u.id);

  return [
    {
      id: "6b5f4ae8-6ee4-47f1-9055-bdc5f9de7a4f",
      seller_id: vendorsId[0] as string,
      name: "Cold-Pressed Extra Virgin Coconut Oil",
      description: "100% pure, multi-purpose coconut oil. Excellent for keto cooking, skin hydration, and hair care.",
      category: "Oils & Condiments",
      image_url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRHnSHk4pUj2UC0RTtd-PgSIsXIxMmLdcX8lN4S_GE0qMQ79TPqdwBiaM6kD7_pmwrDIjVm4CbpsJYTK7Zf7dEV94-15Nz7fw",
      video_url: "https://www.w3schools.com/html/mov_bbb.mp4", 
      total_quantity: 45,
      number_per_portion: 1,
      quantity_unit: "Bottle",
      status: "pending",
      portion_size: 1,
      price_per_portion: 5500,
      available_portions: 20,
      location: "Lagos, Nigeria",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "a5d6a216-5291-4743-8c08-b2c5df9b6d67",
      seller_id: vendorsId[1] as string,
      name: "Organic Hibiscus (Zobo) Leaves",
      description: "Sun-dried premium hibiscus flowers. Rich in antioxidants and perfect for refreshing chilled tea.",
      category: "Beverages",
      image_url: "https://donacefoods.com/wp-content/uploads/2023/11/Product-11.png",
      video_url: "https://www.w3schools.com/html/movie.mp4",
      total_quantity: 200,
      number_per_portion: 1,
      quantity_unit: "Kg",
      status: "pending",
      portion_size: 1,
      price_per_portion: 2500,
      available_portions: 85,
      location: "Kano, Nigeria",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "4e90db1e-f139-4d23-b91d-b54003b4b6d7",
      seller_id: vendorsId[0] as string,
      name: "Hand-Woven Raffia Storage Basket",
      description: "Eco-friendly, artisan-crafted baskets for home organization or stylish shopping.",
      category: "Home & Decor",
      image_url: "https://www.afrahouse.com/cdn/shop/products/natural-raffia-bagafrahouseafrican-art-978951.jpg?v=1705243252&width=1646",
      video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
      total_quantity: 30,
      number_per_portion: 1,
      quantity_unit: "Piece",
      status: "pending",
      portion_size: 1,
      price_per_portion: 8500,
      available_portions: 12,
      location: "Akwa Ibom, Nigeria",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "a19c06cf-0105-4a3a-b47d-3dba36d2707b",
      seller_id: vendorsId[1] as string,
      name: "Smoked Catfish Fillets",
      description: "Oven-dried, sand-free smoked catfish. Vacuum-sealed to maintain freshness and aroma.",
      category: "Proteins",
      image_url: "https://www.bluelifehub.com/wp-content/uploads/2023/03/Smoked-Catfish-from-Tradition-to-Export.png",
      video_url: "https://www.w3schools.com/html/movie.mp4",
      total_quantity: 150,
      number_per_portion: 4,
      quantity_unit: "Pack",
      status: "pending",
      portion_size: 1,
      price_per_portion: 4500,
      available_portions: 40,
      location: "Ibadan, Oyo State",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "8e2519e0-ccf2-4a7d-a272-f1c849878f24",
      seller_id: vendorsId[0] as string,
      name: "Pure Wildflower Honey",
      description: "Unfiltered, raw honey sourced directly from local apiaries. No added sugar.",
      category: "Pantry",
      image_url: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1000&auto=format&fit=crop",
      video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
      total_quantity: 60,
      number_per_portion: 1,
      quantity_unit: "Jar",
      status: "pending",
      portion_size: 500,
      price_per_portion: 3800,
      available_portions: 15,
      location: "Epe, Lagos State",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "02a2f321-3de1-4a35-b1e4-71574e98fc0a",
      seller_id: vendorsId[1] as string,
      name: "Natural Shea Butter (Raw)",
      description: "Grade A unrefined shea butter. Perfect for DIY skincare and treating dry skin.",
      category: "Beauty",
      image_url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop",
      video_url: "https://www.w3schools.com/html/movie.mp4",
      total_quantity: 80,
      number_per_portion: 1,
      quantity_unit: "Tub",
      status: "pending",
      portion_size: 250,
      price_per_portion: 2200,
      available_portions: 30,
      location: "Minna, Niger State",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "89c276bb-c06b-4a5b-bce2-d4a32f88c6f7",
      seller_id: vendorsId[0] as string,
      name: "Gourmet Suya Spice Mix",
      description: "An authentic blend of ginger, peanuts, and peppers. Bring the street flavor home.",
      category: "Spices",
      image_url: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?q=80&w=1000&auto=format&fit=crop",
      video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
      total_quantity: 100,
      number_per_portion: 1,
      quantity_unit: "Sachet",
      status: "pending",
      portion_size: 100,
      price_per_portion: 1500,
      available_portions: 50,
      location: "Abuja, FCT",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "c65a2e36-2236-43b8-bb7b-efb01e80cf52",
      seller_id: vendorsId[1] as string,
      name: "Aged Garlic Powder",
      description: "Finely ground, aromatic garlic powder. Adds depth to any savory dish.",
      category: "Spices",
      image_url: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=1000&auto=format&fit=crop",
      video_url: "https://www.w3schools.com/html/movie.mp4",
      total_quantity: 40,
      number_per_portion: 1,
      quantity_unit: "Bottle",
      status: "pending",
      portion_size: 1,
      price_per_portion: 1800,
      available_portions: 10,
      location: "Jos, Plateau State",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "df26c58b-178a-43ed-9298-22c225d48a3a",
      seller_id: vendorsId[0] as string,
      name: "Yellow Garri (Ijebu Special)",
      description: "Crispy, sour, and perfectly processed yellow garri. Great for drinking or Eba.",
      category: "Grains",
      image_url: "https://images.unsplash.com/photo-1626074353765-517a681e40be?q=80&w=1000&auto=format&fit=crop",
      video_url: "https://www.w3schools.com/html/mov_bbb.mp4",
      total_quantity: 50,
      number_per_portion: 1,
      quantity_unit: "Paint Bucket",
      status: "pending",
      portion_size: 4,
      price_per_portion: 4200,
      available_portions: 0,
      location: "Ijebu Ode, Ogun State",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: "cd2d7eb3-2ac2-4382-9e4d-d6fc1d97ab6e",
      seller_id: vendorsId[1] as string,
      name: "Dried Scent Leaves (Efirin)",
      description: "Carefully dried leaves to preserve essential oils. Essential for pepper soup and black soup.",
      category: "Spices & Herbs",
      image_url: "https://www.everfreshbutchers.co.uk/cdn/shop/products/scentleave25g.jpg?v=1620125061",
      video_url: "https://www.w3schools.com/html/movie.mp4",
      total_quantity: 100,
      number_per_portion: 1,
      quantity_unit: "Pack",
      status: "pending",
      portion_size: 1,
      price_per_portion: 1000,
      available_portions: 0,
      location: "Benin City, Edo State",
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ];
};