import { ProductAttribute } from '@shared/types/product';


export const mockProductSeed: (response)=> Promise<ProductAttribute[]> = ( async (response: {id: string }[]) => {
        const vendorsId = response.map((u) => u.id)
    
    return[
  {
    id: "6b5f4ae8-6ee4-47f1-9055-bdc5f9de7a4f",
    seller_id: vendorsId[0] as string,
    name: "Fresh Sweet Potatoes",
    description: "Naturally grown sweet potatoes — rich in fiber and vitamins, perfect for home and restaurant use.",
    category: "Tubers & Root Crops",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1758641820/prod/o1n11f4wttc7tavfzsnk.jpg",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1758641824/prod/jw6zeudg1hkuuwssk77q.mkv",
    total_quantity: 60,
    number_per_portion: 4,
    quantity_unit: "Pack",
    status: "pending",
    portion_size: 15,
    price_per_portion: 3500,
    available_portions: 13,
    location: "Jos, Plateau State",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "a5d6a216-5291-4743-8c08-b2c5df9b6d67",
    seller_id: vendorsId[1] as string,
    name: "Premium Long Grain Rice",
    description: "High-quality long grain rice with low starch content, ideal for family meals.",
    category: "Grains & Cereals",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1758641296/prod/qf02tpu2auaoxybtpk7x.jpg",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1758641299/prod/pkbga1bkeuj2rupaujwm.mp4",
    total_quantity: 100,
    number_per_portion: 5,
    quantity_unit: "Bag",
    status: "pending",
    portion_size: 20,
    price_per_portion: 3000,
    available_portions: 14,
    location: "Kano, Nigeria",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "4e90db1e-f139-4d23-b91d-b54003b4b6d7",
    seller_id: vendorsId[0] as string,
    name: "Local Ofada Rice",
    description: "Stone-free Ofada rice harvested from Ogun farms — aromatic and healthy.",
    category: "Grains & Cereals",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1758641061/prod/h9pt7tjd6umeucixxgf0.jpg",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1758641063/prod/nqkpasau3bi2pbucmhho.mp4",
    total_quantity: 100,
    number_per_portion: 10,
    quantity_unit: "Bag",
    status: "pending",
    portion_size: 10,
    price_per_portion: 3000,
    available_portions: 6,
    location: "Ogun, Nigeria",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "a19c06cf-0105-4a3a-b47d-3dba36d2707b",
    seller_id: vendorsId[1] as string,
    name: "Golden Parboiled Rice",
    description: "Top-grade parboiled rice with extra shine and fluffy texture when cooked.",
    category: "Grains & Cereals",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1758640698/prod/y6n2xoikxhf7pmbmge1q.jpg",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1758640701/prod/cpuyangvcxc2eby33gp3.mp4",
    total_quantity: 100,
    number_per_portion: 2,
    quantity_unit: "Bag",
    status: "pending",
    portion_size: 50,
    price_per_portion: 3000,
    available_portions: 29,
    location: "Abakaliki, Ebonyi State",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "8e2519e0-ccf2-4a7d-a272-f1c849878f24",
    seller_id: vendorsId[0] as string,
    name: "Brown Beans (Oloyin)",
    description: "High-protein brown beans — perfect for moi-moi, akara, and porridge.",
    category: "Legumes & Pulses",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1758640353/prod/mpqkdbjr51l0pasapu9g.jpg",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1758640357/prod/s1fxhlor3krfe2iwkkgy.mp4",
    total_quantity: 20,
    number_per_portion: 2,
    quantity_unit: "Pack",
    status: "pending",
    portion_size: 10,
    price_per_portion: 1200,
    available_portions: 3,
    location: "Katsina, Nigeria",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "02a2f321-3de1-4a35-b1e4-71574e98fc0a",
    seller_id: vendorsId[1] as string,
    name: "Fresh Yam Tubers",
    description: "Farm-fresh yam tubers directly from Benue — smooth and perfect for pounding.",
    category: "Tubers & Root Crops",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1753448134/dev/kojvqwq1gl19ukxwtgwe.png",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1753448139/dev/yoneaqth3qcygfkhf4mi.mkv",
    total_quantity: 100,
    number_per_portion: 10,
    quantity_unit: "Bunch",
    status: "pending",
    portion_size: 10,
    price_per_portion: 1200,
    available_portions: 4,
    location: "Makurdi, Benue State",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "89c276bb-c06b-4a5b-bce2-d4a32f88c6f7",
    seller_id: vendorsId[0] as string,
    name: "Cassava Tubers",
    description: "Fresh cassava roots ideal for garri, fufu, and other traditional dishes.",
    category: "Tubers & Root Crops",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1753448117/dev/hhfm08rfn6zujou7slt4.png",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1753448122/dev/igz75bttmf88qpyh03l3.mkv",
    total_quantity: 100,
    number_per_portion: 10,
    quantity_unit: "Bunch",
    status: "pending",
    portion_size: 10,
    price_per_portion: 1200,
    available_portions: 1,
    location: "Abeokuta, Ogun State",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "c65a2e36-2236-43b8-bb7b-efb01e80cf52",
    seller_id: vendorsId[1] as string,
    name: "Fresh Plantain Bunches",
    description: "Green and ripe plantains sourced from local farms — sweet and filling.",
    category: "Fruits",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1753448089/dev/elo1s4r0robn0xxws98j.png",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1753448094/dev/qlysm2ojsk5iu8osxoxz.mkv",
    total_quantity: 100,
    number_per_portion: 10,
    quantity_unit: "Bunch",
    status: "pending",
    portion_size: 10,
    price_per_portion: 1200,
    available_portions: 5,
    location: "Sapele, Delta State",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "df26c58b-178a-43ed-9298-22c225d48a3a",
    seller_id: vendorsId[0] as string,
    name: "Taro (Cocoyam)",
    description: "Locally grown cocoyam tubers — excellent for porridge and traditional soups.",
    category: "Tubers & Root Crops",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1753448028/dev/nhojshc6cztuvcpe9imy.png",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1753448032/dev/igeaqztmvi5jiwna54dq.mkv",
    total_quantity: 100,
    number_per_portion: 10,
    quantity_unit: "Bunch",
    status: "pending",
    portion_size: 10,
    price_per_portion: 1200,
    available_portions: 0,
    location: "Nsukka, Enugu State",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "cd2d7eb3-2ac2-4382-9e4d-d6fc1d97ab6e",
    seller_id: vendorsId[1] as string,
    name: "Fresh Ginger Roots",
    description: "Aromatic ginger roots freshly harvested — ideal for tea, spice, and herbal remedies.",
    category: "Spices & Herbs",
    image_url: "https://res.cloudinary.com/di1vgb850/image/upload/v1753447900/dev/q5awtwdodzt9r0kwqutx.png",
    video_url: "https://res.cloudinary.com/di1vgb850/video/upload/v1753447905/dev/qyrcmc3qcbxxi7tl6lxg.mkv",
    total_quantity: 100,
    number_per_portion: 10,
    quantity_unit: "Bunch",
    status: "pending",
    portion_size: 10,
    price_per_portion: 1200,
    available_portions: 0,
    location: "Kaduna, Nigeria",
    createdAt: new Date(),
    updatedAt: new Date()
  }
]});